
import type { FormField, AdminConfig } from './types';
import { 
    FileText, 
    Type, 
    ListTodo, 
    GitMerge, 
    Link2, 
    Paperclip, 
    Users, 
    Bug, 
    GitPullRequest,
    Cloud, 
    Calendar,
    StickyNote,
    Tags,
    Container
} from 'lucide-react';
import { TASK_STATUSES } from './constants';

export const ICONS = {
    text: Type,
    textarea: FileText,
    select: ListTodo,
    multiselect: GitMerge,
    attachments: Paperclip,
    users: Users,
    bug: Bug,
    pr: GitPullRequest,
    deployment: Cloud,
    date: Calendar,
    comments: StickyNote,
    tags: Tags,
    group: Container,
};

export const MASTER_FORM_FIELDS: Record<string, FormField> = {
    title: {
        id: 'title',
        label: 'Title',
        type: 'text',
        placeholder: 'E.g. Fix login button',
        description: 'A short, descriptive title for the task.',
        defaultValue: '',
        icon: 'text',
        group: 'Core Details',
        isCore: true,
    },
    description: {
        id: 'description',
        label: 'Description',
        type: 'textarea',
        placeholder: 'Describe the task in detail...',
        description: 'Provide a thorough description of what needs to be done.',
        defaultValue: '',
        icon: 'textarea',
        group: 'Core Details',
        isCore: true,
    },
    status: {
        id: 'status',
        label: 'Status',
        type: 'select',
        options: [...TASK_STATUSES],
        placeholder: 'Select a status',
        description: 'The current status of the task.',
        defaultValue: 'To Do',
        icon: 'list',
        group: 'Core Details',
        isCore: true,
    },
    developers: {
        id: 'developers',
        label: 'Assigned Developers',
        type: 'tags',
        placeholder: 'Select or create developers',
        description: 'Developers assigned to this task.',
        defaultValue: [],
        icon: 'users',
        group: 'Assignment & Tracking',
    },
    repositories: {
        id: 'repositories',
        label: 'Repositories',
        type: 'tags',
        options: ['UI-Dashboard', 'UI-Admin', 'Templates', 'API-Export'],
        placeholder: 'Select repositories',
        description: 'Code repositories related to this task.',
        defaultValue: [],
        icon: 'multiselect',
        group: 'Assignment & Tracking',
    },
    azureWorkItemId: {
        id: 'azureWorkItemId',
        label: 'Azure Work Item ID',
        type: 'text',
        placeholder: 'Enter Azure ID',
        description: 'The ID of the corresponding Azure DevOps work item.',
        defaultValue: '',
        icon: 'bug',
        group: 'Assignment & Tracking',
    },
    devStartDate: {
        id: 'devStartDate',
        label: 'Dev Start Date',
        type: 'date',
        placeholder: 'Select dev start date',
        description: 'The start date for development.',
        defaultValue: null,
        icon: 'date',
        group: 'Dates',
    },
    devEndDate: {
        id: 'devEndDate',
        label: 'Dev End Date',
        type: 'date',
        placeholder: 'Select dev end date',
        description: 'The end date for development.',
        defaultValue: null,
        icon: 'date',
        group: 'Dates',
    },
    qaStartDate: {
        id: 'qaStartDate',
        label: 'QA Start Date',
        type: 'date',
        placeholder: 'Select QA start date',
        description: 'The start date for QA testing.',
        defaultValue: null,
        icon: 'date',
        group: 'Dates',
    },
    qaEndDate: {
        id: 'qaEndDate',
        label: 'QA End Date',
        type: 'date',
        placeholder: 'Select QA end date',
        description: 'The end date for QA testing.',
        defaultValue: null,
        icon: 'date',
        group: 'Dates',
    },
};


export const DEFAULT_ADMIN_CONFIG: AdminConfig = {
    formLayout: [
        'title', 
        'description', 
        'status',
        'developers',
        'repositories',
        'azureWorkItemId',
        'devStartDate',
        'devEndDate',
        'qaStartDate',
        'qaEndDate',
    ],
    fieldConfig: {
        title: { visible: true, required: true },
        description: { visible: true, required: false },
        status: { visible: true, required: true },
        developers: { visible: true, required: false },
        repositories: { visible: true, required: false },
        azureWorkItemId: { visible: true, required: false },
        devStartDate: { visible: true, required: false },
        devEndDate: { visible: true, required: false },
        qaStartDate: { visible: true, required: false },
        qaEndDate: { visible: true, required: false },
    },
    groupOrder: [
        'Core Details',
        'Assignment & Tracking',
        'Dates',
        'Advanced',
        'Tagging',
        'Custom Fields',
    ],
}
